baseURL = "https://recomedicales.fr/"
copyright = "© 2019-2024 par Jean-Baptiste FRON sous license CC BY-NC 4.0"
DefaultContentLanguage = "fr"
disableHugoGeneratorInject = false
enableInlineShortcodes = true
enableRobotsTXT = true
languageCode = "fr"
removePathAccents = true
rssLimit = 30
summaryLength = 10
title = "RecoMédicales"

[taxonomies]
  specialite = "specialites"
  tag = "tags"
  annee = "annees"

# [[cascade]]
#  [cascade._build]
#    list = 'never'
#    render = 'never'
#  [cascade._target]
#    kind = '{taxonomy,term}'
#    path = '{/specialites,/specialites/**}'

[params]
  author = "Jean-Baptiste FRON"
  dateFormat = "02/01/2006"
  description = "Les dernières recommandations médicales de prise en charge pour la pratique en médecine générale. Bilan de première intention, arbre décisionnel et scores"
  github = "https://github.com/djibe/recommandations-medicales"
  githubUser = "djibe"
  facebook = "https://www.facebook.com/RecoMedicales"
  linkedin = "https://www.linkedin.com/company/recom%C3%A9dicales/"
  ogimage = "/images/icons/banner-og.jpg"
  icon = "/android-chrome-512x512.png"
  SidebarRecentLimit = 5

# todo
[related.indices]
  name = "specialites"

# https://gohugo.io/templates/output-formats/#output-formats-for-pages
# search https://learn.netlify.app/en/basics/configuration/
[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS", "WebAppManifest", "WORKER"]
  section = ["HTML", "JSON"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[outputFormats]
  [outputFormats.WORKER]
  mediaType = "text/javascript"
  baseName = "sw"
  isPlainText = true

# Dependencies
[params.cdn]
  material_js = "https://cdn.jsdelivr.net/npm/djibe-material@4.6.2-1.0/js/material.min.js"
  material_js_hash = "sha256-B6009p2rnV9Tx+3+m0kEff8HiL9uJ2wE11zD7zgZ82g="
  css =         "css/style.css"
  bs_js =       "https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
  bs_js_hash =  "sha256-GRJrh0oydT1CwS36bBeJK/2TggpaUQC6GzTaTQdZm0k="
  jquery =      "https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"
  jquery_hash = "sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="

[params.dateformat]
# HTML doc : https://developer.mozilla.org/fr/docs/Web/HTML/Element/time
  #date = 2006-01-02
  #datetime = "2006-01-02T15:04:05Z0700"  # html ISO 8601 datetimeformat

[privacy.youTube]
  privacyEnhanced = true

[markup.goldmark.extensions]
  strikethrough = false
[markup.goldmark.extensions.extras.delete]
  enable = true
[markup.goldmark.extensions.extras.mark]
  enable = true
[markup.goldmark.extensions.extras.subscript]
  enable = true
[markup.goldmark.extensions.extras.superscript]
  enable = true
[markup.goldmark.parser]
  autoHeadingIDType = 'github'
[markup.goldmark.parser.attribute]
  block = true # Allow classes on HTML entities
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md

[menu]
  [[menu.main]]
    identifier = "recommandations"
    name = "Recommandations"
    url = "/recommandations/"
    weight = 2
  [[menu.main]]
    identifier = "cabinet"
    name = "Cabinet"
    url = "/cabinet/"
    weight = 3
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles/"
    weight = 4
  [[menu.main]]
    identifier = "actualites"
    name = "Actualités"
    url = "/actualites/"
    weight = 5
  [[menu.main]]
    identifier = "tags"
    name = "Mots-clés"
    url = "/tags/"
    weight = 6

